### PR TITLE
fix: ensure k8s bootstrap is idempotent

### LINKED ISSUE #17: Error configuring machine when Canonical K8s is already bootstrapped
## Description

Most of concierge's commands are idempotent. For instance, `concierge prepare` won't error out if the `k8s` snap is already installed, it will simply move on. However, `concierge prepare` errors out if Canonical K8s is already bootstrapped. This feels like an unintended behavior.

## Expected behavior

`concierge prepare` doesn't error out when Canonical K8s is already bootstrapped. 

## Environment

- **Concierge**: latest/stable:    0.9.1 2024-11-18
- **K8s**: v1.30.6 2024-11-19 (1621) 108MB classic

## Logs

```
guillaume@courge:~$ sudo concierge prepare -p k8s --k8s-channel=1.30-classic/beta --lxd-channel "5.21/stable" --verbose
[sudo] password for guillaume: 
time=2024-11-19T09:10:05.904-05:00 level=INFO msg="Preset selected" preset=k8s
time=2024-11-19T09:10:06.359-05:00 level=DEBUG msg="Filesystem ownership changed" user=guillaume group=1000 path=/home/guillaume/.cache
time=2024-11-19T09:10:06.359-05:00 level=DEBUG msg="Filesystem ownership changed" user=guillaume group=1000 path=/home/guillaume/.cache/concierge/concierge.yaml
time=2024-11-19T09:10:06.359-05:00 level=DEBUG msg="Merged runtime configuration saved" path=.cache/concierge/concierge.yaml
time=2024-11-19T09:10:06.361-05:00 level=DEBUG msg="Running command" command="/usr/bin/apt-get update"
time=2024-11-19T09:10:06.361-05:00 level=DEBUG msg="Installing snap" snap=charmcraft
time=2024-11-19T09:10:07.006-05:00 level=DEBUG msg="Queried snapd API" snap=charmcraft installed=true classic=true
time=2024-11-19T09:10:07.006-05:00 level=DEBUG msg="Running command" command="/usr/bin/snap refresh charmcraft --channel latest/stable --classic"
time=2024-11-19T09:10:07.474-05:00 level=INFO msg="Refreshed snap" snap=charmcraft
time=2024-11-19T09:10:07.474-05:00 level=DEBUG msg="Installing snap" snap=jq
time=2024-11-19T09:10:07.847-05:00 level=DEBUG msg="Queried snapd API" snap=jq installed=true classic=false
time=2024-11-19T09:10:07.847-05:00 level=DEBUG msg="Running command" command="/usr/bin/snap refresh jq --channel latest/stable"
time=2024-11-19T09:10:08.332-05:00 level=INFO msg="Refreshed snap" snap=jq
time=2024-11-19T09:10:08.332-05:00 level=DEBUG msg="Installing snap" snap=yq
time=2024-11-19T09:10:08.482-05:00 level=DEBUG msg="Running command" command="/usr/bin/apt-get install -y python3-pip"
time=2024-11-19T09:10:08.661-05:00 level=DEBUG msg="Queried snapd API" snap=yq installed=true classic=false
time=2024-11-19T09:10:08.661-05:00 level=DEBUG msg="Running command" command="/usr/bin/snap refresh yq --channel latest/stable"
time=2024-11-19T09:10:08.685-05:00 level=INFO msg="Installed apt package" package=python3-pip
time=2024-11-19T09:10:08.685-05:00 level=DEBUG msg="Running command" command="/usr/bin/apt-get install -y python3-venv"
time=2024-11-19T09:10:08.894-05:00 level=INFO msg="Installed apt package" package=python3-venv
time=2024-11-19T09:10:09.116-05:00 level=INFO msg="Refreshed snap" snap=yq
time=2024-11-19T09:10:09.116-05:00 level=DEBUG msg="Installing snap" snap=rockcraft
time=2024-11-19T09:10:09.429-05:00 level=DEBUG msg="Queried snapd API" snap=rockcraft installed=true classic=true
time=2024-11-19T09:10:09.429-05:00 level=DEBUG msg="Running command" command="/usr/bin/snap refresh rockcraft --channel latest/stable --classic"
time=2024-11-19T09:10:09.926-05:00 level=INFO msg="Refreshed snap" snap=rockcraft
time=2024-11-19T09:10:09.926-05:00 level=DEBUG msg="Installing snap" snap=lxd
time=2024-11-19T09:10:09.926-05:00 level=DEBUG msg="Installing snap" snap=k8s
time=2024-11-19T09:10:10.539-05:00 level=DEBUG msg="Queried snapd API" snap=k8s installed=true classic=true
time=2024-11-19T09:10:10.539-05:00 level=DEBUG msg="Running command" command="/usr/bin/snap refresh k8s --channel 1.30-classic/beta --classic"
time=2024-11-19T09:10:10.689-05:00 level=DEBUG msg="Queried snapd API" snap=lxd installed=true classic=false
time=2024-11-19T09:10:11.044-05:00 level=INFO msg="Refreshed snap" snap=k8s
time=2024-11-19T09:10:11.044-05:00 level=DEBUG msg="Installing snap" snap=kubectl
time=2024-11-19T09:10:11.044-05:00 level=DEBUG msg="Running command" command="/usr/bin/snap refresh lxd --channel 5.21/stable"
time=2024-11-19T09:10:11.685-05:00 level=INFO msg="Refreshed snap" snap=lxd
time=2024-11-19T09:10:11.685-05:00 level=DEBUG msg="Running command" command="/snap/bin/lxd waitready"
time=2024-11-19T09:10:11.739-05:00 level=DEBUG msg="Running command" command="/snap/bin/lxd init --minimal"
time=2024-11-19T09:10:11.792-05:00 level=DEBUG msg="Queried snapd API" snap=kubectl installed=true classic=true
time=2024-11-19T09:10:11.792-05:00 level=DEBUG msg="Running command" command="/usr/bin/snap refresh kubectl --channel stable --classic"
time=2024-11-19T09:10:11.856-05:00 level=DEBUG msg="Running command" command="/snap/bin/lxc network set lxdbr0 ipv6.address none"
time=2024-11-19T09:10:11.898-05:00 level=DEBUG msg="Running command" command="/usr/bin/chmod a+wr /var/snap/lxd/common/lxd/unix.socket"
time=2024-11-19T09:10:11.899-05:00 level=DEBUG msg="Running command" command="/usr/sbin/usermod -a -G lxd guillaume"
time=2024-11-19T09:10:11.923-05:00 level=DEBUG msg="Running command" command="/usr/sbin/iptables -F FORWARD"
time=2024-11-19T09:10:11.924-05:00 level=DEBUG msg="Running command" command="/usr/sbin/iptables -P FORWARD ACCEPT"
time=2024-11-19T09:10:11.939-05:00 level=INFO msg="Prepared provider" provider=lxd
time=2024-11-19T09:10:12.397-05:00 level=INFO msg="Refreshed snap" snap=kubectl
time=2024-11-19T09:10:12.397-05:00 level=DEBUG msg="Running command" command="/snap/bin/k8s bootstrap"
Command: /snap/bin/k8s bootstrap
Output:
Error: The node is already part of a cluster
time=2024-11-19T09:10:13.445-05:00 level=DEBUG msg="Running command" command="/snap/bin/k8s bootstrap"
Command: /snap/bin/k8s bootstrap
Output:
Error: The node is already part of a cluster
time=2024-11-19T09:10:15.490-05:00 level=DEBUG msg="Running command" command="/snap/bin/k8s bootstrap"
Command: /snap/bin/k8s bootstrap
Output:
Error: The node is already part of a cluster
time=2024-11-19T09:10:19.541-05:00 level=DEBUG msg="Running command" command="/snap/bin/k8s bootstrap"
Command: /snap/bin/k8s bootstrap
Output:
Error: The node is already part of a cluster
time=2024-11-19T09:10:27.587-05:00 level=DEBUG msg="Running command" command="/snap/bin/k8s bootstrap"
Command: /snap/bin/k8s bootstrap
Output:
Error: The node is already part of a cluster
time=2024-11-19T09:10:43.653-05:00 level=DEBUG msg="Running command" command="/snap/bin/k8s bootstrap"
Command: /snap/bin/k8s bootstrap
Output:
Error: The node is already part of a cluster
time=2024-11-19T09:11:15.732-05:00 level=DEBUG msg="Running command" command="/snap/bin/k8s bootstrap"
Command: /snap/bin/k8s bootstrap
Output:
Error: The node is already part of a cluster
time=2024-11-19T09:12:19.792-05:00 level=DEBUG msg="Running command" command="/snap/bin/k8s bootstrap"
Command: /snap/bin/k8s bootstrap
Output:
Error: The node is already part of a cluster
time=2024-11-19T09:14:27.834-05:00 level=DEBUG msg="Running command" command="/snap/bin/k8s bootstrap"
Command: /snap/bin/k8s bootstrap
Output:
Error: The node is already part of a cluster
time=2024-11-19T09:15:12.440-05:00 level=DEBUG msg="Running command" command="/snap/bin/k8s bootstrap"
Command: /snap/bin/k8s bootstrap
Output:
Error: The node is already part of a cluster
time=2024-11-19T09:15:12.488-05:00 level=ERROR msg="Failed to configure machine" error="failed to install K8s: exit status 1"
```

### PR DESCRIPTION
**Pull request by jnsgruk**
Fixes #17 

@gruyaume can you give this a test locally and ensure it solves things for you?

### CODE REVIEW

**Comment by gruyaume** [comment]
> Fixes #17
> 
> @gruyaume can you give this a test locally and ensure it solves things for you?

Yes this solves the issue.

It's not quite related, but in the Canonical K8s I had deployed locally, I didn't have network enabled. Concierge will not enable network and error out when enabling load-balancer (which depends on network).

## Logs

```
guillaume@courge:~/concierge$ sudo ./concierge prepare -p k8s --k8s-channel=1.30-classic/beta --lxd-channel "5.21/stable" --verbose
[sudo] password for guillaume: 
time=2024-11-19T11:49:12.131-05:00 level=INFO msg="Preset selected" preset=k8s
time=2024-11-19T11:49:12.517-05:00 level=DEBUG msg="Filesystem ownership changed" user=guillaume group=1000 path=/home/guillaume/.cache
time=2024-11-19T11:49:12.517-05:00 level=DEBUG msg="Filesystem ownership changed" user=guillaume group=1000 path=/home/guillaume/.cache/concierge/concierge.yaml
time=2024-11-19T11:49:12.517-05:00 level=DEBUG msg="Merged runtime configuration saved" path=.cache/concierge/concierge.yaml
time=2024-11-19T11:49:12.517-05:00 level=DEBUG msg="Running command" command="/usr/bin/apt-get update"
time=2024-11-19T11:49:12.517-05:00 level=DEBUG msg="Installing snap" snap=jq
time=2024-11-19T11:49:13.129-05:00 level=DEBUG msg="Queried snapd API" snap=jq installed=true classic=false
time=2024-11-19T11:49:13.129-05:00 level=DEBUG msg="Running command" command="/usr/bin/snap refresh jq --channel latest/stable"
time=2024-11-19T11:49:13.664-05:00 level=INFO msg="Refreshed snap" snap=jq
time=2024-11-19T11:49:13.664-05:00 level=DEBUG msg="Installing snap" snap=yq
time=2024-11-19T11:49:14.101-05:00 level=DEBUG msg="Queried snapd API" snap=yq installed=true classic=false
time=2024-11-19T11:49:14.101-05:00 level=DEBUG msg="Running command" command="/usr/bin/snap refresh yq --channel latest/stable"
time=2024-11-19T11:49:14.677-05:00 level=INFO msg="Refreshed snap" snap=yq
time=2024-11-19T11:49:14.677-05:00 level=DEBUG msg="Installing snap" snap=rockcraft
time=2024-11-19T11:49:14.830-05:00 level=DEBUG msg="Running command" command="/usr/bin/apt-get install -y python3-pip"
time=2024-11-19T11:49:15.025-05:00 level=DEBUG msg="Queried snapd API" snap=rockcraft installed=true classic=true
time=2024-11-19T11:49:15.025-05:00 level=DEBUG msg="Running command" command="/usr/bin/snap refresh rockcraft --channel latest/stable --classic"
time=2024-11-19T11:49:15.034-05:00 level=INFO msg="Installed apt package" package=python3-pip
time=2024-11-19T11:49:15.034-05:00 level=DEBUG msg="Running command" command="/usr/bin/apt-get install -y python3-venv"
time=2024-11-19T11:49:15.233-05:00 level=INFO msg="Installed apt package" package=python3-venv
time=2024-11-19T11:49:15.475-05:00 level=INFO msg="Refreshed snap" snap=rockcraft
time=2024-11-19T11:49:15.475-05:00 level=DEBUG msg="Installing snap" snap=charmcraft
time=2024-11-19T11:49:15.938-05:00 level=DEBUG msg="Queried snapd API" snap=charmcraft installed=true classic=true
time=2024-11-19T11:49:15.938-05:00 level=DEBUG msg="Running command" command="/usr/bin/snap refresh charmcraft --channel latest/stable --classic"
time=2024-11-19T11:49:16.423-05:00 level=INFO msg="Refreshed snap" snap=charmcraft
time=2024-11-19T11:49:16.423-05:00 level=DEBUG msg="Installing snap" snap=lxd
time=2024-11-19T11:49:16.423-05:00 level=DEBUG msg="Installing snap" snap=k8s
time=2024-11-19T11:49:16.938-05:00 level=DEBUG msg="Queried snapd API" snap=k8s installed=true classic=true
time=2024-11-19T11:49:16.938-05:00 level=DEBUG msg="Running command" command="/usr/bin/snap refresh k8s --channel 1.30-classic/beta --classic"
time=2024-11-19T11:49:17.082-05:00 level=DEBUG msg="Queried snapd API" snap=lxd installed=true classic=false
time=2024-11-19T11:49:17.376-05:00 level=INFO msg="Refreshed snap" snap=k8s
time=2024-11-19T11:49:17.376-05:00 level=DEBUG msg="Installing snap" snap=kubectl
time=2024-11-19T11:49:17.376-05:00 level=DEBUG msg="Running command" command="/usr/bin/snap refresh lxd --channel 5.21/stable"
time=2024-11-19T11:49:17.856-05:00 level=INFO msg="Refreshed snap" snap=lxd
time=2024-11-19T11:49:17.857-05:00 level=DEBUG msg="Running command" command="/snap/bin/lxd waitready"
time=2024-11-19T11:49:17.907-05:00 level=DEBUG msg="Running command" command="/snap/bin/lxd init --minimal"
time=2024-11-19T11:49:17.979-05:00 level=DEBUG msg="Queried snapd API" snap=kubectl installed=true classic=true
time=2024-11-19T11:49:17.979-05:00 level=DEBUG msg="Running command" command="/usr/bin/snap refresh kubectl --channel stable --classic"
time=2024-11-19T11:49:18.031-05:00 level=DEBUG msg="Running command" command="/snap/bin/lxc network set lxdbr0 ipv6.address none"
time=2024-11-19T11:49:18.076-05:00 level=DEBUG msg="Running command" command="/usr/bin/chmod a+wr /var/snap/lxd/common/lxd/unix.socket"
time=2024-11-19T11:49:18.077-05:00 level=DEBUG msg="Running command" command="/usr/sbin/usermod -a -G lxd guillaume"
time=2024-11-19T11:49:18.129-05:00 level=DEBUG msg="Running command" command="/usr/sbin/iptables -F FORWARD"
time=2024-11-19T11:49:18.130-05:00 level=DEBUG msg="Running command" command="/usr/sbin/iptables -P FORWARD ACCEPT"
time=2024-11-19T11:49:18.145-05:00 level=INFO msg="Prepared provider" provider=lxd
time=2024-11-19T11:49:18.446-05:00 level=INFO msg="Refreshed snap" snap=kubectl
time=2024-11-19T11:49:18.447-05:00 level=DEBUG msg="Running command" command="/snap/bin/k8s status"
time=2024-11-19T11:49:19.502-05:00 level=DEBUG msg="Running command" command="/snap/bin/k8s status --wait-ready"
time=2024-11-19T11:49:20.559-05:00 level=DEBUG msg="Running command" command="/snap/bin/k8s set load-balancer.l2-mode=true"
time=2024-11-19T11:49:20.614-05:00 level=DEBUG msg="Running command" command="/snap/bin/k8s set load-balancer.cidrs=10.43.45.0/28"
time=2024-11-19T11:49:20.668-05:00 level=DEBUG msg="Running command" command="/snap/bin/k8s enable load-balancer"
Command: /snap/bin/k8s enable load-balancer
Output:
Enabling load-balancer on the cluster. This may take a few seconds, please wait.
Error: Failed to enable load-balancer on the cluster.

The error was: failed to PUT /k8sd/cluster/config: database transaction to update cluster configuration failed: failed to update cluster configuration: failed to update cluster config: updated cluster configuration is not valid: load-balancer requires network to be enabled
time=2024-11-19T11:49:21.714-05:00 level=DEBUG msg="Running command" command="/snap/bin/k8s enable load-balancer"
Command: /snap/bin/k8s enable load-balancer
Output:
Enabling load-balancer on the cluster. This may take a few seconds, please wait.
Error: Failed to enable load-balancer on the cluster.

The error was: failed to PUT /k8sd/cluster/config: database transaction to update cluster configuration failed: failed to update cluster configuration: failed to update cluster config: updated cluster configuration is not valid: load-balancer requires network to be enabled
time=2024-11-19T11:49:23.758-05:00 level=DEBUG msg="Running command" command="/snap/bin/k8s enable load-balancer"
Command: /snap/bin/k8s enable load-balancer
Output:
Enabling load-balancer on the cluster. This may take a few seconds, please wait.
Error: Failed to enable load-balancer on the cluster.

The error was: failed to PUT /k8sd/cluster/config: database transaction to update cluster configuration failed: failed to update cluster configuration: failed to update cluster config: updated cluster configuration is not valid: load-balancer requires network to be enabled
time=2024-11-19T11:49:27.807-05:00 level=DEBUG msg="Running command" command="/snap/bin/k8s enable load-balancer"
Command: /snap/bin/k8s enable load-balancer
Output:
Enabling load-balancer on the cluster. This may take a few seconds, please wait.
Error: Failed to enable load-balancer on the cluster.

The error was: failed to PUT /k8sd/cluster/config: database transaction to update cluster configuration failed: failed to update cluster configuration: failed to update cluster config: updated cluster configuration is not valid: load-balancer requires network to be enabled
time=2024-11-19T11:49:35.862-05:00 level=DEBUG msg="Running command" command="/snap/bin/k8s enable load-balancer"
Command: /snap/bin/k8s enable load-balancer
Output:
Enabling load-balancer on the cluster. This may take a few seconds, please wait.
Error: Failed to enable load-balancer on the cluster.

The error was: failed to PUT /k8sd/cluster/config: database transaction to update cluster configuration failed: failed to update cluster configuration: failed to update cluster config: updated cluster configuration is not valid: load-balancer requires network to be enabled
time=2024-11-19T11:49:51.920-05:00 level=DEBUG msg="Running command" command="/snap/bin/k8s enable load-balancer"
Command: /snap/bin/k8s enable load-balancer
Output:
Enabling load-balancer on the cluster. This may take a few seconds, please wait.
Error: Failed to enable load-balancer on the cluster.

The error was: failed to PUT /k8sd/cluster/config: database transaction to update cluster configuration failed: failed to update cluster configuration: failed to update cluster config: updated cluster configuration is not valid: load-balancer requires network to be enabled
```

**Comment by jnsgruk** [comment]
Hmm that's weird - network should be enabled by default. Either way we can explicitly enable it for sure - can you open another issue and I'll look at it tomorrow/later this week?

**Comment by gruyaume** [comment]
> Hmm that's weird - network should be enabled by default. Either way we can explicitly enable it for sure - can you open another issue and I'll look at it tomorrow/later this week?

Yes, network is enabled by default, but if you have a pre-existing Canonical K8s environment where network was disabled, then you run `concierge prepare`, concierge will not enable network.

**Comment by jnsgruk** [comment]
Ah interesting. Yeh in that case I'll add it to the things to enable at least for the presets

**Pull request merged**
